---
# tasks file for cloud-ecs

- debug: var=item_c

- set_fact:
    cluster_userdata: "{{ lookup('template', 'lcg_userdata.j2') }}"

- name: ECS | Create Launch Config
  ec2_lc:
    name: "{{ item_c.name }}-lc"
    state: present
    instance_type: "{{ item_c.instance_type }}"
    image_id: "{{ item_c.ami_id }}"
    key_name: "{{ item_c.key_name |d(omit) }}"
    region: "{{ item_c.region |d(omit) }}"
    security_groups: "{{ item_c.security_groups }}"
    vpc_id: "{{ item_c.vpc_id | default(omit) }}"
    instance_profile_name: "{{ item_c.instance_profile_name |d(omit) }}"
    user_data: "{{ cluster_userdata }}"

- name: Create Auto Scaling Group
  ec2_asg:
    name: "{{ item_c.name }}-asg"
    launch_config_name: "{{ item_c.name }}-lc"
    min_size: "{{ item_c.asg_min_size }}"
    max_size: "{{ item_c.asg_max_size }}"
    region: "{{ item_c.region }}"
    availability_zones: "{{ item_c.zones }}"
    vpc_zone_identifier: "{{ item_c.subnets }}"
    tags:
      - Name: "{{ item_c.name }}-ecs-instance"

- name: Create ECS Cluster
  ecs_cluster:
    name: "{{ item_c.name }}"
    state: present
